repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        exclude: (^.git/|^.venv/|^__pycache__/|^dist/|^tests/)
        language: system
        types:
          - python
